version: 2
jobs:
  build:
    working_directory: ~/client
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install yarn package manager
          command: curl -o- -L https://yarnpkg.com/install.sh | bash
      - restore_cache: # special step to restore the dependency cache
          keys:
            - yarn-packages-{{ checksum "./yarn.lock" }}
            - yarn-packages-
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          paths:
            - ~/client/.cache/yarn
          key: yarn-packages-{{ checksum "./yarn.lock" }}
      - run: # run tests
          name: Run Test and Coverage
          environment:
            JEST_SUITE_NAME: jest tests
            JEST_JUNIT_OUTPUT_DIR: ./test-results/junit/jest/
            JEST_JUNIT_OUTPUT_NAME: client-test-results.xml
          command: |
            mkdir -p ./test-results/junit/jest
            yarn run test:ci
      - store_test_results:
          path: ./test-results/junit/jest
      - run:
          name: Compile react build
          command: yarn run build
