version: 2
jobs:
  build:
    work_directory: ~/MayThe4thBeRussov2
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-
      - run:
          name: Install ci-yarn-upgrade Globally
          command: yarn add ci-yarn-upgrade -G
      - run: ci-yarn-upgrade --execute --latest --verbose;
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: # run tests
          name: Run Test and Coverage
          command: |
            ./cc-test-reporter before-build
            npm test -- -u --coverage
            ./cc-test-reporter after-build --exit-code $?
      - store_artifacts: 
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
      - run:
          name: Compile react build
          command: npm run build
