version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install yarn package manager
          command: curl -o- -L https://yarnpkg.com/install.sh | bash
      - restore_cache: # special step to restore the dependency cache
          keys:
            - yarn-packages-{{ checksum "./client/yarn.lock" }}
            - yarn-packages-
      - run:
          name: Install Dependencies
          command: cd client && yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          paths:
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "./client/yarn.lock" }}

      - run:
          name: Make directory to store test results
          command: mkdir test-results
      - run:
          name: Make directory to store test results from jest
          command: mkdir test-results/jest
      - run: # run tests
          name: Run Test and Coverage
          command: |
            cd client
            yarn run test:ci
      - store_test_results:
          path: ~/test-results/jest
      - run:
          name: Compile react build
          command: cd client && yarn run build
