version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Setup Dependencies
          command: cd client && npm install
      - save_cache:
          paths:
            - /client/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: # run tests
          name: Run Test and Coverage
          command: |
            cd client
            npm run test:ci
      - run:
          name: Compile react build
          command: cd client && npm run build
