export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCESS = 'LOGIN_USER_SUCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const RETRIEVE_COMMENT_DATA = 'RETRIEVE_COMMENT_DATA';
export const SAVE_COMMENT_DATA = 'SAVE_COMMENT_DATA';